# Generated by Django 4.0.3 on 2022-04-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='bio',
        ),
    ]
