# Generated by Django 4.0.3 on 2022-04-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_remove_blogger_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='summary',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
